server:
  port: 8080
  servlet:
    context-path: /carmanagement

spring:
  datasource:
    url: "jdbc:mysql://root:BtabatiqSSQELrdLqPqjvTXvHXkiySbT@junction.proxy.rlwy.net:12093/railway"
    username: "root"
    password: BtabatiqSSQELrdLqPqjvTXvHXkiySbT
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /documentforvananh