server:
  port: 8080
  servlet:
    context-path: /carmanagement

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/car_management"
    username: "root"
    password: 123456

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    show-sql: true
