#server.port=8080
#server.servlet.context-path=/carmanagement
#
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MyDatabase;encrypt=false
#spring.datasource.username=sa
#spring.datasource.password=123456aA@$
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#springdoc.swagger-ui.path=/documentforvananh
#server:
  port: 8080
  servlet:
    context-path: /carmanagement

spring:
  datasource:
    url: ${MYSQL_URL:}
    password: ${MYSQL_USERNAME:}
    username: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /documentforvananh