server:
  port: 8080
  servlet:
    context-path: /carmanagement

spring:
  datasource:
    url: ${MYSQL_URL:}
    username: ${MYSQL_USERNAME:}
    password: ${MYSQL_PASSWORD:}

  jpa:
    hibernate:
      #ddl-auto: create
      ddl-auto: none
    show-sql: true
